spring:
  application:
    name : QuoraApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database : quora_db
      auto-index-creation : true
  elasticsearch:
     uris: http://localhost:9200/


  app:
    feed:
      # how many items to keep in the per-user cached timeline (LIST)
      cacheSize: 12
      pageSize: 4


